### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by timreichen** [postcss/postcss-deno#3]
Not an issue, but what is the advantage of this module over using a cdn like esm.sh, jspm.dev, skypack.dev or unpkg.com?

**Comment by oscarotero** [comment]
Automatic conversions don't work in all cases. This is the "official" version of postcss, that use [deno native dependencies](https://github.com/postcss/postcss-deno/blob/master/deps.js) (with the exception of source-map) and runs the same tests, to ensure that it does not fail.

**Comment by shadowtime2000** [comment]
Also I don't believe JSPM Skypack or Unpkg would actually work with this because it uses `fs` for some stuff.

**Comment by timreichen** [comment]
I actually use postcss in a deno project with esm.sh. Seems to work fine as for now, so I am wondering if there is any good reason to switch to this official version for that use case.
@shadowtime2000 I am not sure if postcss really uses `fs`, I think some plugins do though.

**Comment by shadowtime2000** [comment]
@timreichen 

> I actually use postcss in a deno project with esm.sh. Seems to work fine as for now, so I am wondering if there is any good reason to switch to this official version for that use case.

CommonJS to ES conversions can be pretty buggy because of CJS's dynamic nature. As @oscarotero said, conversions like that don't always work. This gives a little more of a guarantee of stability because it is official and most likely the maintainers of PostCSS will be making sure that they stay compatible.

> @shadowtime2000 I am not sure if postcss really uses fs, I think some plugins do though.

Check @oscarotero [message in #1](https://github.com/postcss/postcss-deno/issues/1#issuecomment-759075208)

**Comment by shadowtime2000** [comment]
Should we enable discussions on this repo then convert this to a discussion? Seems like a better way cc @oscarotero

**Comment by oscarotero** [comment]
@shadowtime2000 No sure about that. This repo contains only the automatic conversion of the original node postcss code. Discussions for postcss should be in the main repository. The only relevant question in this repo is why using the deno code instead jspm/esm.js and creating a discussions section for only one topic makes no sense to me.
