### ISSUE TITLE
PostCSS 8.3 is not published

### ISSUE THREAD

**Issue by valtlai** [postcss/postcss-deno#5]
Publishing [PostCSS 8.3.0](https://github.com/postcss/postcss/releases/tag/8.3.0) failed. I think this probably relates to source map changes.

**Comment by oscarotero** [comment]
Ok, fixed the dependency.

I have to update the [Deno port of source_map](https://github.com/oscarotero/deno-source-map) with the changes in source-map-js at some point. But it's only a performance improvement, not a breaking change.
